<?php

return [
    'audio_cache' => [
        'dir' => env('CALL_CENTER_AUDIO_CACHE_DIR', 'call-center/audio-cache'),
        'alt_dir' => env('CALL_CENTER_ALT_AUDIO_CACHE_DIR', 'call-center/alt/audio-cache'),
        'retention_days' => (int) env('CALL_CENTER_AUDIO_CACHE_RETENTION_DAYS', 10),
    ],
    'checklists' => [
        'storage_path' => env('CALL_CENTER_CHECKLISTS_PATH', 'call-center/checklists.json'),
        'alt_storage_path' => env('CALL_CENTER_ALT_CHECKLISTS_PATH', 'call-center/alt/checklists.json'),
    ],
    'automation' => [
        'timezone' => env('CALL_CENTER_AUTOMATION_TIMEZONE', 'Europe/Kyiv'),
        'night_start_time' => env('CALL_CENTER_AUTOMATION_NIGHT_START_TIME', ''),
        'night_end_time' => env('CALL_CENTER_AUTOMATION_NIGHT_END_TIME', ''),
        'night_start_hour' => (int) env('CALL_CENTER_AUTOMATION_NIGHT_START_HOUR', 20),
        'night_end_hour' => (int) env('CALL_CENTER_AUTOMATION_NIGHT_END_HOUR', 6),
    ],
    'transcription' => [
        'max_upload_kb' => (int) env('CALL_CENTER_TRANSCRIPTION_MAX_UPLOAD_KB', 102400),
        'settings_path' => env('CALL_CENTER_TRANSCRIPTION_SETTINGS_PATH', 'call-center/settings.json'),
        'alt_settings_path' => env('CALL_CENTER_ALT_TRANSCRIPTION_SETTINGS_PATH', 'call-center/alt/settings.json'),
        'tasks_dir' => env('CALL_CENTER_TRANSCRIPTION_TASKS_DIR', 'call-center/transcription-tasks'),
        'alt_tasks_dir' => env('CALL_CENTER_ALT_TRANSCRIPTION_TASKS_DIR', 'call-center/alt/transcription-tasks'),
        'python_binary' => env('CALL_CENTER_PYTHON_BINARY', 'python3'),
        'script_path' => base_path('scripts/faster_whisper_transcribe.py'),
        'storage_dir' => env('CALL_CENTER_TRANSCRIPTION_STORAGE_DIR', 'call-center/transcriptions'),
        'alt_storage_dir' => env('CALL_CENTER_ALT_TRANSCRIPTION_STORAGE_DIR', 'call-center/alt/transcriptions'),
        'cache_dir' => env('FASTER_WHISPER_CACHE_DIR', 'call-center/faster-whisper-cache'),
        'model' => env('FASTER_WHISPER_MODEL', 'large-v3'),
        'initial_prompt' => env('FASTER_WHISPER_INITIAL_PROMPT', ''),
        'available_models' => [
            'tiny',
            'base',
            'small',
            'medium',
            'large-v3',
        ],
        'device' => env('FASTER_WHISPER_DEVICE', 'cpu'),
        'compute_type' => env('FASTER_WHISPER_COMPUTE_TYPE', 'int8'),
        'beam_size' => (int) env('FASTER_WHISPER_BEAM_SIZE', 5),
        'vad_filter' => filter_var(env('FASTER_WHISPER_VAD_FILTER', true), FILTER_VALIDATE_BOOL),
        'timeout_seconds' => (int) env('FASTER_WHISPER_TIMEOUT', 1800),
        'word_timestamps' => filter_var(env('FASTER_WHISPER_WORD_TIMESTAMPS', true), FILTER_VALIDATE_BOOL),
        'diarization' => [
            'enabled' => filter_var(env('CALL_CENTER_SPEAKER_DIARIZATION_ENABLED', false), FILTER_VALIDATE_BOOL),
            'provider_model' => env('CALL_CENTER_SPEAKER_DIARIZATION_MODEL', 'pyannote/speaker-diarization-community-1'),
            'auth_token' => env('PYANNOTE_AUTH_TOKEN', ''),
            'num_speakers' => (int) env('CALL_CENTER_SPEAKER_DIARIZATION_NUM_SPEAKERS', 2),
            'merge_gap_seconds' => (float) env('CALL_CENTER_SPEAKER_DIARIZATION_MERGE_GAP_SECONDS', 0.8),
        ],
    ],
    'evaluation' => [
        'enabled' => filter_var(env('CALL_CENTER_CHECKLIST_EVALUATION_ENABLED', true), FILTER_VALIDATE_BOOL),
        'jobs_dir' => env('CALL_CENTER_EVALUATION_JOBS_DIR', 'call-center/evaluation-jobs'),
        'alt_jobs_dir' => env('CALL_CENTER_ALT_EVALUATION_JOBS_DIR', 'call-center/alt/evaluation-jobs'),
        'provider' => env('CALL_CENTER_CHECKLIST_EVALUATION_PROVIDER', 'ollama'),
        'ollama_url' => env('CALL_CENTER_OLLAMA_URL', 'http://llm_yaprofi_ollama:11434'),
        'api_key' => env('CALL_CENTER_OLLAMA_API_KEY', ''),
        'ollama_model' => env('CALL_CENTER_OLLAMA_MODEL', 'qwen2.5:7b'),
        'think' => filter_var(env('CALL_CENTER_OLLAMA_THINK', false), FILTER_VALIDATE_BOOL),
        'timeout_seconds' => (int) env('CALL_CENTER_OLLAMA_TIMEOUT', 600),
        'background_timeout_seconds' => (int) env('CALL_CENTER_OLLAMA_BACKGROUND_TIMEOUT', 7200),
        'temperature' => (float) env('CALL_CENTER_OLLAMA_TEMPERATURE', 0.2),
        'options' => [
            'num_ctx' => (int) env('CALL_CENTER_OLLAMA_NUM_CTX', 4096),
            'top_k' => (int) env('CALL_CENTER_OLLAMA_TOP_K', 40),
            'top_p' => (float) env('CALL_CENTER_OLLAMA_TOP_P', 0.9),
            'repeat_penalty' => (float) env('CALL_CENTER_OLLAMA_REPEAT_PENALTY', 1.1),
            'seed' => env('CALL_CENTER_OLLAMA_SEED', ''),
            'num_predict' => (int) env('CALL_CENTER_OLLAMA_NUM_PREDICT', 256),
        ],
    ],
];
